version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: chat_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  chat-application:
    build: .
    container_name: chat-application
    ports:
      - "3000:3000"
    env_file:
      - .env 
    depends_on:
      - mysql
    command: ["npm", "run", "start:prod"]

volumes:
  mysql_data:
